name: Run Swift Test and Build

on:
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Swift
        uses: SwiftActions/setup-swift@v2
        with:
          swift-version: "5.9"

      - name: Build
        run: swift build

      - name: Test
        run: swift test
