name: Run Swift Test and Build

on:
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"

      - name: Build
        run: swift build

      - name: Test
        run: swift test --enable-code-coverage

      - name: Produce LCOV Report
        uses: hashmapsdata2value/spm-lcov-action@0.1.0
        with:
          output-file: ./coverage/lcov.info
